name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: docker/setup-compose-action@v1
      - run: npm install -g pnpm
      - run: pnpm install
      - run: docker compose build db
      - run: docker compose up -d db
      - run: sleep 10 # wait for db to be ready
      - run: pnpm prettier:check

      - run: pnpm test:unit
      - run: pnpm test:integration
      - run: pnpm build
